/**
 * Suggestions Table (Admin Tickets)
 * Users can submit suggestions, but cannot see others' submissions.
 */

-- migrate:up
create table public.suggestions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text,
  status text not null default 'new' -- For admin workflow (e.g., new, under_review, closed)
);

comment on table public.suggestions is 'Private suggestions for admin review, like tickets.';

alter table public.suggestions enable row level security;

-- Users can create suggestions.
create policy "Users can create suggestions"
on public.suggestions for insert
to authenticated with check (true);

-- NOTE: There is no SELECT policy for users. This means they cannot read from this table.
-- Admins will use the service_role key to bypass RLS and view all suggestions.

-- migrate:down
drop table if exists public.suggestions;
