-- filepath: c:\Users\Owner\OneDrive\Desktop\friendship-community-circle\supabase\migrations\002.sql
create table public.suggestions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text
);