-- filepath: c:\Users\Owner\OneDrive\Desktop\friendship-community-circle\supabase\migrations\002.sql
create table public.suggestions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone not null default now(),
  title text not null,
  description text,
  status text not null default 'new' -- For admin workflow (e.g., new, under_review, closed)
);

comment on table public.suggestions is 'Private suggestions for admin review, like tickets.';

alter table public.suggestions enable row level security;

-- Users can create suggestions.
create policy "Users can create suggestions"
on public.suggestions for insert
to authenticated with check (true);

-- migrate:down
drop table if exists public.suggestions;